export const DEFAULT_DECK = [
  "3 Ambitious Farmhand",
  "4 Reckoner Bankbuster",
  "2 Elspeth Resplendent",
  "2 March of Otherworldly Light",
  "4 The Restoration of Eiganjo",
  "4 Roadside Reliquary",
  "1 Eiganjo, Seat of the Empire",
  "16 Plains",
  "4 Ossification",
  "4 Wedding Announcement",
  "2 Destroy Evil",
  "4 The Wandering Emperor",
  "4 Lay Down Arms",
  "3 The Eternal Wanderer",
  "3 Mirrex",
  "3 Depopulate",
  "2 Fateful Absence",
  "3 Farewell",
  "4 Sunset Revelry",
  "3 Loran of the Third Path",
];
